// starters/vue/src/App.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import {
  useCategories,
  usePaymentMethods,
  useProducts,
  usePurchase,
  useShop,
  type NovaPaymentMethodId,
  type NovaProduct,
  type NovaPurchaseRequest,
} from '@novasynx/storefront-sdk/vue'

const { shop, loading: shopLoading, error: shopError } = useShop()
const { categories } = useCategories()
const { methods } = usePaymentMethods()
const {
  products,
  loading: productsLoading,
  error: productsError,
  reload: reloadProducts,
} = useProducts()
const {
  purchase,
  loading: purchaseLoading,
  error: purchaseError,
  result: purchaseResult,
} = usePurchase()

const selectedCategory = ref<string | undefined>()

const shopName = computed(() => shop.value?.name ?? 'Nova Shop')
const shopCurrency = computed(() => shop.value?.currency ?? 'RUB')
const categoryList = computed(() => categories.value)
const productList = computed(() => products.value)
const paymentMethod = computed<NovaPaymentMethodId | null>(() => methods.value[0]?.id ?? null)
const paymentUrl = computed(() => purchaseResult.value?.payUrl ?? null)
const isBuying = computed(() => purchaseLoading.value)

function formatPrice(price: number) {
  return new Intl.NumberFormat('ru-RU').format(price)
}

async function selectCategory(category?: string) {
  selectedCategory.value = category
  await reloadProducts(category)
}

async function buy(product: NovaProduct) {
  const method = paymentMethod.value
  if (!method) return

  const request: NovaPurchaseRequest = {
    productId: product.id,
    quantity: 1,
    paymentMethod: method,
  }

  const order = await purchase(request)
  if (order.payUrl) window.location.assign(order.payUrl)
}
</script>

<template>
  <div class="app">
    <div v-if="shopLoading" class="loader">
      <div class="spinner"></div>
      <p>Загрузка магазина...</p>
    </div>

    <div v-else-if="shopError" class="error">
      <p>{{ shopError }}</p>
    </div>

    <template v-else>
      <header class="header">
        <h1 class="logo">{{ shopName }}</h1>
        <nav class="nav" aria-label="Категории">
          <button
            type="button"
            class="nav-link"
            :class="{ active: !selectedCategory }"
            @click="selectCategory(undefined)"
          >
            Все
          </button>
          <button
            v-for="cat in categoryList"
            :key="cat"
            type="button"
            class="nav-link"
            :class="{ active: selectedCategory === cat }"
            @click="selectCategory(cat)"
          >
            {{ cat }}
          </button>
        </nav>
      </header>

      <main class="main">
        <section class="hero">
          <h2>{{ shopName }}</h2>
          <p>Выберите товар из каталога</p>
        </section>

        <p v-if="productsError" class="inline-error">{{ productsError }}</p>
        <p v-if="purchaseError" class="inline-error">{{ purchaseError }}</p>
        <a v-if="paymentUrl" :href="paymentUrl" class="payment-link">
          Открыть оплату
        </a>

        <section class="catalog">
          <div v-if="productsLoading" class="loader compact">
            <div class="spinner"></div>
          </div>
          <div v-else-if="!productList.length" class="empty">
            Нет товаров в выбранной категории
          </div>
          <div v-else class="products-grid">
            <article v-for="product in productList" :key="product.id" class="product-card">
              <img
                v-if="product.image"
                :src="product.image"
                :alt="product.name"
                class="product-image"
              />
              <div v-else class="product-image-placeholder">
                Нет изображения
              </div>
              <div class="product-info">
                <h3 class="product-name">{{ product.name }}</h3>
                <span class="product-category">{{ product.category }}</span>
                <div class="product-footer">
                  <span class="product-price">
                    {{ formatPrice(product.price) }} {{ shopCurrency }}
                  </span>
                  <button
                    type="button"
                    class="btn-buy"
                    :disabled="isBuying || !paymentMethod"
                    @click="buy(product)"
                  >
                    {{ isBuying ? 'Создание...' : 'Купить' }}
                  </button>
                </div>
              </div>
            </article>
          </div>
        </section>
      </main>

      <footer class="footer">
        <p>&copy; {{ new Date().getFullYear() }} {{ shopName }}</p>
      </footer>
    </template>
  </div>
</template>

// starters/react/src/App.tsx
import { useMemo, useState } from 'react'
import {
  useCategories,
  usePaymentMethods,
  useProducts,
  usePurchase,
  useShop,
  type NovaPaymentMethodId,
  type NovaProduct,
  type NovaPurchaseRequest,
} from '@novasynx/storefront-sdk/react'

function formatPrice(price: number) {
  return new Intl.NumberFormat('ru-RU').format(price)
}

export function App() {
  const { shop, loading: shopLoading, error: shopError } = useShop()
  const { categories } = useCategories()
  const { methods } = usePaymentMethods()
  const {
    products,
    loading: productsLoading,
    error: productsError,
    reload: reloadProducts,
  } = useProducts()
  const {
    purchase,
    loading: purchaseLoading,
    error: purchaseError,
    result: purchaseResult,
  } = usePurchase()
  const [selectedCategory, setSelectedCategory] = useState<string | undefined>()

  const paymentMethod = useMemo<NovaPaymentMethodId | null>(
    () => methods[0]?.id ?? null,
    [methods],
  )

  async function selectCategory(category?: string) {
    setSelectedCategory(category)
    await reloadProducts(category)
  }

  async function buy(product: NovaProduct) {
    if (!paymentMethod) return

    const request: NovaPurchaseRequest = {
      productId: product.id,
      quantity: 1,
      paymentMethod,
    }

    const order = await purchase(request)
    if (order.payUrl) window.location.assign(order.payUrl)
  }

  if (shopLoading) {
    return (
      <div className="loader">
        <div className="spinner" />
        <p>Загрузка магазина...</p>
      </div>
    )
  }

  if (shopError) {
    return (
      <div className="error">
        <p>{shopError}</p>
      </div>
    )
  }

  const shopName = shop?.name ?? 'Nova Shop'
  const shopCurrency = shop?.currency ?? 'RUB'

  return (
    <div className="app">
      <header className="header">
        <h1 className="logo">{shopName}</h1>
        <nav className="nav" aria-label="Категории">
          <button
            type="button"
            className={`nav-link ${!selectedCategory ? 'active' : ''}`}
            onClick={() => selectCategory(undefined)}
          >
            Все
          </button>
          {categories.map((cat) => (
            <button
              key={cat}
              type="button"
              className={`nav-link ${selectedCategory === cat ? 'active' : ''}`}
              onClick={() => selectCategory(cat)}
            >
              {cat}
            </button>
          ))}
        </nav>
      </header>

      <main className="main">
        <section className="hero">
          <h2>{shopName}</h2>
          <p>Выберите товар из каталога</p>
        </section>

        {productsError ? <p className="inline-error">{productsError}</p> : null}
        {purchaseError ? <p className="inline-error">{purchaseError}</p> : null}
        {purchaseResult?.payUrl ? (
          <a href={purchaseResult.payUrl} className="payment-link">
            Открыть оплату
          </a>
        ) : null}

        <section className="catalog">
          {productsLoading ? (
            <div className="loader compact">
              <div className="spinner" />
            </div>
          ) : products.length === 0 ? (
            <div className="empty">Нет товаров в выбранной категории</div>
          ) : (
            <div className="products-grid">
              {products.map((product) => (
                <article key={product.id} className="product-card">
                  {product.image ? (
                    <img src={product.image} alt={product.name} className="product-image" />
                  ) : (
                    <div className="product-image-placeholder">Нет изображения</div>
                  )}
                  <div className="product-info">
                    <h3 className="product-name">{product.name}</h3>
                    <span className="product-category">{product.category}</span>
                    <div className="product-footer">
                      <span className="product-price">
                        {formatPrice(product.price)} {shopCurrency}
                      </span>
                      <button
                        type="button"
                        className="btn-buy"
                        disabled={purchaseLoading || !paymentMethod}
                        onClick={() => buy(product)}
                      >
                        {purchaseLoading ? 'Создание...' : 'Купить'}
                      </button>
                    </div>
                  </div>
                </article>
              ))}
            </div>
          )}
        </section>
      </main>

      <footer className="footer">
        <p>&copy; {new Date().getFullYear()} {shopName}</p>
      </footer>
    </div>
  )
}
